apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
spec:
  selector:
    matchLabels:
      app: security-pod
  template:
    metadata:
      labels:
        app: security-pod
    spec:
      containers:
        - name: security-container
          image: therapymicroservices.azurecr.io/therapy_security-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 7011
