version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "4300:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    depends_on:
      - config-server

  gateway-service:
    build: ./gateway-service
    ports:
      - "4302:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  config-server:
    build: ./config-server
    ports:
      - "4301:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  appointment-service:
    build: ./appointment-service
    ports:
      - "4303:7007"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/appointment?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  healthrecordandexpertise-service:
    build: ./healthrecordandexpertise
    ports:
      - "4304:7008"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/healthrecordandexpertise?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  patient-service:
    build: ./patient-service
    ports:
      - "4305:7009"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/patient?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  physiotherapist-service:
    build: ./physiotherapist-service
    ports:
      - "4306:7010"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/physiotherapist?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  security-service:
    build: ./security-service
    ports:
      - "4307:7011"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/security?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  social-service:
    build: ./social-service
    ports:
      - "4308:7012"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/social?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  therapy-service:
    build: ./therapy-service
    ports:
      - "4309:7013"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/therapy?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

