version: '3.8'

networks:
  therapy-net:
    driver: bridge

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    #environment:
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
#      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
#      - EUREKA_CLIENT_FETCH_REGISTRY=false
    depends_on:
      - config-server
    networks:
      - therapy-net



  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      #- eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
#      - eureka.client.register.with.eureka=false
#      - eureka.client.fetch.registry=false
    depends_on:
      - config-server
      - eureka-server
    networks:
      - therapy-net

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - therapy-net

  appointment-service:
    build: ./appointment-service
    ports:
      - "4303:7007"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/appointment?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - therapy-net

  healthrecordandexpertise-service:
    build: ./healthrecordandexpertise-service
    ports:
      - "4304:7008"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/healthrecordandexpertise?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - therapy-net

  patient-service:
    build: ./patient-service
    ports:
      - "4305:7009"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/patient?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - therapy-net

  physiotherapist-service:
    build: ./physiotherapist-service
    ports:
      - "4306:7010"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/physiotherapist?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - therapy-net

  security-service:
    build: ./security-service
    ports:
      - "4307:7011"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/security?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - therapy-net

  social-service:
    build: ./social-service
    ports:
      - "4308:7012"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/social?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - therapy-net

  therapy-service:
    build: ./therapy-service
    ports:
      - "4309:7013"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://therapy-microservices.mysql.database.azure.com:3306/therapy?useSSL=true&serverTimeZone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin_therapy
      - SPRING_DATASOURCE_PASSWORD=XnySqs63R65w5KT
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - therapy-net
