server.port: 7013
server.error.include-message: always


logging:
level:
root: INFO
se.magnus: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimeZone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: security-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
      instance:
      leaseRenewalIntervalInSeconds: 5
      leaseExpirationDurationInSeconds: 5




