apiVersion: apps/v1
kind: Deployment
metadata:
  name: physiotherapist-deployment
spec:
  selector:
    matchLabels:
      app: physiotherapist-pod
  template:
    metadata:
      labels:
        app: physiotherapist-pod
    spec:
      containers:
        - name: physiotherapist-container
          image: therapymicroservices.azurecr.io/therapy_physiotherapist-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 7010
